routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'SiteController@index')->name('home');

Route::get('/load/{limit}', 'SiteController@load')->name('load');

Route::get('/about/{id}', 'SiteController@about')->name('about');

Route::get('/my_portfolio', 'SiteController@my_portfolio')->name('my_portfolio')->middleware('user');

Route::get('/services/{id?}', 'ServicesController@services')->name('services');

Route::get('/service-load/{limit}/{view}', 'ServicesController@load')->name('load');

Route::get('/search/{search?}', 'ServicesController@search')->name('search');

Route::get('/getAllResume', 'ServicesController@filter')->name('filter');

Route::get('/getSubSection/{section}', 'ServicesController@getSubSection')->name('getSubSection');

Route::get('/getDistricts/{region}', 'ServicesController@getDistricts')->name('getDistricts');

Route::post('/feedback', 'SiteController@feedback')->name('feedback');
// Route::get('/search', function () {
//     return view('search');
// })->name('search');

// Route::get('/services_btn-mob', function () {
//     return view('services_btn-mob');
// })->name('services_btn-mob');

// Route::get('/filter-mob', function () {
//     return view('filter-mob');
// })->name('filter-mob');


Auth::routes(['verify' => true]);
Route::post('/change-password', 'ChangePasswordController@change')->name('change.password')->middleware('user');
Route::post('/account/create-resume', 'AccountController@resumeSave')->name('create.resume')->middleware('user');
Route::post('/account/check-resume', 'AccountController@isSaveResume')->name('check.resume')->middleware('user');
Route::post('/removeAva', 'AccountController@removeAvaImg')->name('removeAvaImg')->middleware('user');
Route::post('/removeLicense', 'AccountController@removeLicense')->name('removeLicense')->middleware('user');
Route::post('/removePortfolio', 'AccountController@removePortfolio')->name('removePortfolio')->middleware('user');
Route::post('/updateResume/{id}', 'AccountController@updateResume')->name('updateResume')->middleware('user');

Route::get('/admin', 'HomeController@index')->name('admin')->middleware('admin');
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::resource('sections', 'SectionController');
    Route::resource('sub-sections', 'SubSectionController');
    Route::resource('regions', 'RegionController');
    Route::resource('packets', 'PacketController');
    Route::resource('feedbacks', 'FeedbackController');
    Route::resource('licenses', 'LicenseController');
    Route::resource('portfolios', 'PortfolioController');
    Route::resource('ads-banner', 'AdsController');
    Route::get('users', 'UserController@index')->name('users.index');
    Route::get('users/{user}/edit', 'UserController@edit')->name('user.edit');
    Route::put('users/{user}', 'UserController@update')->name('user.update');
    Route::get('users/create', 'UserController@create')->name('users.create');
    Route::post('users/store', 'UserController@store')->name('users.store');
});

// Настройки ролей

// Route::get('/role', 'Controller@index')->name('role');

// Route::get('/addRole', 'Controller@addRole')->name('addRole');

app/Http/Controllers/SiteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Packet;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use App\Models\Section;
use App\Models\SubSection;
use App\Models\Region;
use App\Models\Resume;
use App\Models\Portfolio;
use App\Models\License;
use App\Models\Feedback;
use App\Models\AdsBanner;

use Session;

class SiteController extends Controller
{

    public function __construct()
    {
        //$this->middleware('guest')->except('my_portfolio');
    }

    /**
   * Show the application dashboard.
   *
   * @return \Illuminate\Contracts\Support\Renderable
   */
  public function index()
  {
    $sections = Section::all();
    $subsections = SubSection::with('section')->get();
    $regions = Region::orderBy('name', 'ASC')->get();

    $vip_user_ids = User::select('id')->whereHas('roles', function ($query) {
      $query->where('name','vip')->orWhere('name','profi');
    })->get();
    $topUserCards = Resume::whereIn('user_id', $vip_user_ids)->with('user')->with('section')->with('sub_section')->withCount('feedbacks')->inRandomOrder()->limit(3)->get();

    $user_ids = User::whereHas('roles', function ($query) {
        $query->where('name','!=','admin');
    })->whereNotIn('id', $vip_user_ids)->pluck('id');
    $plainUsersCards = Resume::whereIn('user_id', $user_ids)->with('user')->with('section')->with('sub_section')->withCount('feedbacks')->take(3)->orderBy('created_at','DESC')->get();
    $plainUsersCount = 0;
    if (count($user_ids) > 0) {
      $plainUsersCount = Resume::whereIn('user_id', $user_ids)->count();
    }

    $ads_right = AdsBanner::where('isActive', 1)->where('page_name','Главная')->where('name','Правый Блок')->first();
    $ads_bottom = AdsBanner::where('isActive', 1)->where('page_name','Главная')->where('name','Нижний блок')->first();

    return view('site/index', [
        'sections' => $sections,
        'subsections' => $subsections,
        'regions' => $regions,
        'topUserCards' => $topUserCards,
        'plainUsersCards' => $plainUsersCards,
        'plainUsersCount' => $plainUsersCount,
        'ads_right' => $ads_right,
        'ads_bottom' => $ads_bottom,
    ]);
  }

    public function load($limit)
    {
      $vip_user_ids = User::select('id')->whereHas('roles', function ($query) {
        $query->where('name','vip')->orWhere('name','profi');
      })->get();
      $user_ids = User::whereHas('roles', function ($query) {
        $query->where('name','!=','admin');
      })->whereNotIn('id', $vip_user_ids)->pluck('id');
      $plainUsersCards = Resume::whereIn('user_id', $user_ids)->with('user')->with('section')->with('sub_section')->withCount('feedbacks')->take($limit)->orderBy('created_at','DESC')->get();

      return (String) view('site/plainUsers', [
          'plainUsersCards' => $plainUsersCards,
      ]);
    }

  public function my_portfolio()
  {
    $user = Auth::user();
    $resumes = Resume::where('user_id', $user->id)->with('licenses')->with('region')->with('section')->with('sub_section')->withCount('feedbacks')->with('user')->with('portfolios')->get();
    $portfolios = Portfolio::where('user_id', $user->id)->get();
    $licenses = License::where('user_id', $user->id)->get();
    $packets = Packet::all();

    $sections = Section::all();
    $subsections = SubSection::with('section')->get();
    $regions = Region::orderBy('name', 'ASC')->get();
    return view('my_portfolio', compact(['packets', 'user', 'resumes', 'portfolios', 'licenses', 'sections', 'subsections', 'regions']));
  }

  public function about($id)
  {
    $resume = Resume::where('id', $id)
      ->with('region')
      ->with('section')
      ->with('sub_section')
      ->with('user')
      ->with('district')
      ->withCount('feedbacks')
      ->firstOrFail();
    if (!Session::has('viewed')) {
      if (Auth::guest() || Auth::user()->id != $resume->user_id) {
        $resume->viewed = $resume->viewed + 1;
        $resume->save();
        Session::put('viewed', 'viewed');
      }
    }

    $portfolios = Portfolio::where('resume_id', $id)->where('isActive', 1)->get();
    $licenses = License::where('resume_id', $id)->where('isActive', 1)->get();

    $dopUsluga = Resume::where('user_id', $resume->user_id)->get();
    $feedbacks = Feedback::where('resume_id', $resume->id)->where('isActive', 1)->get();

    $vip_user_ids = User::select('id')->whereHas('roles', function ($query) {
        $query->where('name','vip')->orWhere('name','profi');
    })->get();
    $recommendationUsers = Resume::whereIn('user_id', $vip_user_ids)->where('id', '!=', $id)->where('sub_section_id', $resume->sub_section_id)->with('user')->with('section')->with('sub_section')->get();

    $regions = Region::orderBy('name', 'ASC')->get();
    $sections = Section::all();
    $subsections = SubSection::with('section')->get();
    return view('about/index', [
        // 'user' => $user,
        'resume' => $resume,
        'portfolios' => $portfolios,
        'licenses' => $licenses,
        'recommendationUsers' => $recommendationUsers,
        'regions' => $regions,
        'sections' => $sections,
        'subsections' => $subsections,
        'dopUsluga' => $dopUsluga,
        'feedbacks' => $feedbacks,
        'ableToComment' => $this->ableToComment($resume->id, Auth::id(), request()->ip())
    ]);
  }

    public function feedback(Request $request)
    {
        if ($this->ableToComment($request->resume_id, Auth::id(), $request->ip())) {

            $this->validate($request, [
                'resume_id' => 'required|integer|exists:resume,id',
                'user_id' => 'required|integer|exists:users,id',
                'fio' => 'required|string|max:60000|min:1',
                'review' => 'required|string|max:60000|min:1',
            ]);

            $feedback = Feedback::create($request->all());

            if (auth()->check()) {
                $feedback->sender_id = Auth::id();
            } else {
                $feedback->ip = $request->ip();
            }

            $feedback->save();
        }

        return redirect()->back();
    }

    protected function ableToComment($resumeId, $userId, $userIP)
    {
        $feedbackQuery = Feedback::query();
        $feedbackQuery->where('resume_id', $resumeId);

        if (auth()->check()) {
            $feedbackQuery->where('sender_id', $userId);
        } else {
            $feedbackQuery->where('ip', $userIP);
        }
        $feedback = $feedbackQuery->take(1)->get()->toArray();

        return empty($feedback);
    }
}

resources/views/site/index.blade.php
@extends('layouts.main')
@section('pageTitle','Главная')
@section('content')
@section('template','index')
@section('namespace','index')
    <div class="fon-wrapper">
        <div class="fon"></div>
    </div>
    <div class="top_specialistsAbsolute flex">
        <div class="top_specialistsAbsolute__star">
            <i class="icon-start_top"></i>
        </div>
        <div class="top_specialistsAbsolute__word">
            Top
        </div>
    </div>

    <div class="newListingsAbsolute">
        <div class="newListingsAbsolute__plus">
            <i class = "icon-newListingsPlus"></i>
        </div>
        <div class="newListingsAbsolute__word">
            <p>new</p>
        </div>
    </div>
    <div class="images_back">
        <div class="stamp">
            <img src="images/samples/stamp.png" />
        </div>
        <div class="leaf3">
            <img src="images/samples/leaf3.png" />
        </div>
        <div class="leaf4">
            <img src="images/samples/leaf4.png" />
        </div>
        <div class="leaf9">
            <img src="images/samples/leaf9.png" />
        </div>
        <div class="cup">
            <img src="images/samples/cup.png" />
        </div>
    </div>
    <div class="container-fluid">
        <!-- <div class="topTitle flex web"> -->
        <!-- <div class="topTitle__flex">
            <div class="blockMain">МОИ УСЛУГИ</div>
            <div class="blockSecond">–  услуги всего Казахстана</div>
        </div> -->
        <!-- </div> -->
        <!-- <div class="topTitle mob">
            <p class="topTitle__p"><span>МОИ УСЛУГИ</span> <br> услуги всего Казахстана</p>
        </div>  -->
        <div class="topTitle webTitle">
            <span>МОИ УСЛУГИ</span>
            <p class="topTitle__p">портал объединяющий заказчиков <br> и исполнителей услуг</p>
        </div>
        <div class="topTitle mob">
            <span>МОИ УСЛУГИ</span>
            <p class="topTitle__p">портал объединяющий заказчиков и исполнителей услуг</p>
        </div>
        @include('site.search')
        <div class="services">
            @if( !empty($sections))
                @foreach ($sections as $section)
                    <div class="services__clicked_block post_section" data-id="{{ $section->id }}">
                        <div class="left" style="background-image: url('storage/{{ $section->img }}')">
                            <div class="icon-block" style = "background-image: url(../images/svg-src/svg_internet.svg);"></div>
                        </div>
                        <div class="right">
                            <div class="sub-services">
                                <div class="title">{{ $section->name }}</div>
                                <div class="flex justify-content-between list_services">
                                    @if( !empty($subsections))
                                        <div class="block">
                                            @foreach ($subsections as $subsection)
                                                @if( $subsection->section_id == $section->id)
                                                    <ul>
                                                        <li>
                                                            <a href="/services/{{$subsection->id}}">{{ $subsection->name }}</a>
                                                        </li>
                                                    </ul>
                                                @endif
                                            @endforeach
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="close flex" id = 'close-servicesBlock'>
                                <i class='icon-arrow_near_button'></i>
                                <span>Закрыть {{ $section->name }}</span>
                            </div>
                        </div>
                    </div>
                @endforeach
            @endif
            <div class="row flex" id = "services-inactive">
                @if( !empty($sections))
                    @foreach ($sections as $section)
                        <div class="outside-offset">
                            <a href="#" class="services__items show_subsection" data-id="{{ $section->id }}">
                                <img src="storage/{{ $section->img }}">
                                <div class="services_information flex">
                                    <p>{{ $section->name }}</p>
                                    <div class="arrow_and_link flex	">
                                        <i class="icon-arrow_near_button"></i>
                                        <span class="onclick-checked">Подробнее</span>
                                    </div>
                                </div>
                            </a>
                        </div>
                    @endforeach
                @endif
            </div>
        </div>
    @include('site.topUsers')
    </div>
    <div class="container-fluid">
        @if ($ads_bottom != null)
            <div class="horizontal-advertizing" style="background-image: url({{ asset('storage/').'/'.$ads_bottom->img }});"></div>
        @endif
        @if( !empty($plainUsersCards))
            <div class="new_listings">
                <div class="new_listings__title">
                    <span> Новые объявления </span>
                </div>
            </div>
            <div id="post-plain-users">
                @include('site.plainUsers')
            </div>
            <div class="download">
                <a href="#" id="load-more" data-limit="6" data-max="{{ $plainUsersCount }}">Загрузить еще</a>
            </div>
        @endif
    </div>
@endsection

resources/views/site/plainUsers.blade.php
@foreach ($plainUsersCards as $card)
    <div class="listings_blocks flex">
        <div class="listings_blocks__left">
            <div class="avatar" style="background-image: url({{ $card->Big_img != null ? asset('storage/portfolio/').'/'.$card->user_id.'/'.$card->Big_img : '' }})"></div>
        </div>
        <div class="listings_blocks__rigth">
            <div class="flex justify-content-between">
                <div class="emlpoyee_info">
                    <p class="employee_position">{{$card->section->name}}</p>
                    <p class="employee_name">{{ $card->user->last_name }} {{ $card->user->first_name }} {{ $card->user->patronymic }} <span>{{$card->sub_section->name}}</span></p>
                </div>
                <div class="listings_blocks_buttons">
                    <!-- <button onclick="location.href='https://api.whatsapp.com/send?phone={{ $card->whatsapp }}'" class="btn btn_writeWhatssap">Написать в WhatsApp</button> -->
                    <form action="https://wa.me/{{str_replace([' ', '(', ')', '-'], '', $card->whatsapp)}}" target="_blank" style="margin-bottom:15px;">
                      <button class="btn btn_writeWhatssap">
                                Написать в WhatsApp
                      </button>
                    </form>
                    <button onclick="location.href='/about/{{ $card->id }}'" class="btn btn_details">Подробнее</button>
                </div>
            </div>
            <div class="reviews_right">
                <div class="review_flexed flex ">
                    <i class="icon-review_svg"></i>
                    <p>отзывы: {{ $card->feedbacks_count }}</p>
                </div>
            </div>
        </div>
    </div>
@endforeach
<div class="mob_listings">
    @foreach ($plainUsersCards as $card)
        <div class="listining_block_mob">
            <div class="left flex">
                <div class="avatar-image-mob">
                    <img src="{{$card->Big_img != null ? asset('storage/portfolio/').'/'.$card->user_id.'/'.$card->Big_img : ''}}" />
                </div>
                <div class="left-second">
                    <div class="top-title"> {{$card->section->name}} </div>
                    <div class="name">{{ $card->user->last_name }} {{ $card->user->first_name }} {{ $card->user->patronymic }}</div>
                    <div class="info">{{$card->sub_section->name}}</div>
                </div>
            </div>
            <div class="right flex">
                <div class="reviews flex">
                    <i class="icon-review_svg"></i>
                    <p>отзывы: {{ $card->feedbacks_count }}</p>
                </div>
                <div class="buttons flex">
                    <button onclick="location.href='/about/{{ $card->id }}'" class="btn btn_btnSmallMob flex">
                        <i class="icon-mob_arrow_near_button"></i> Подробнее </button>
                    <button onclick="location.href='https://wa.me/{{str_replace([' ', '(', ')', '-'], '', $card->whatsapp)}}'" class="btn btn_btnSmallMob flex">
                        <i class="icon-mob_arrow_near_button"></i> WhatsApp </button>
                </div>
            </div>
        </div>
    @endforeach
</div>

resources/views/site/search.blade.php
<form id="searchForm" class="menu" method="get" action="{{route('services')}}" class = "searchPromptParent">
    <div class="menu_block flex">
        <div class="menu_block__custom-select ">
            <select class="menu-items parts" name="section_id">
                <option selected disabled>Разделы</option>
                @if( !empty($sections))
                    @foreach ($sections as $section)
                        <option value="{{ $section->id }}">{{ $section->name }}</option>
                    @endforeach
                @endif
            </select>
        </div>
        <div class="menu_block__custom-select" id="second-select">
            <select class="menu-items city" name="region_id">
                <option selected disabled>Города</option>
                @if( !empty($regions))
                    @foreach ($regions as $region)
                        <option value="{{ $region->id }}">{{ $region->name }}</option>
                    @endforeach
                @endif
            </select>
        </div>
        <div class="menu_block__search-block" id='searched' >
            <input type="text" placeholder="Поиск" name = "search" class = 'searchElem' id="search_name" autocomplete="off">            
            <div class="prompt_words">
                <div class = 'prompt_words__info' id="prompt_words__sections">                    
                    <ul>
                        <li>
                            Дом
                        </li>
                        <li>
                        Интернет услуги
                        </li>
                        <li>
                        Образование
                        </li>
                        <li>
                        Красота и здоровье
                        </li>
                        <li>
                        Менеджмент
                        </li>
                        <li>
                        Автомобиль
                        </li>
                    </ul>
                </div>
            </div>            
        </div>
    </div>
    <button type="submit" class="btn btn_large btn_shadow">Искать</button>
</form>

resources/views/site/topUsers.blade.php
@if( !empty($topUserCards))
    <div class="top-title2 flex top-title2__line">
        <span> Tоp специалистов </span>
    </div>
    <div class="flex">
        <div class="top-specialists web">
            @foreach ($topUserCards as $card)
                <div class="top_set">
                    <div class="top-specialists__information {{$card->user->hasRole('vip') ? 'vip_border' : 'profi_border'}}">
                        <div class="first {{$card->user->hasRole('vip') ? 'vip' : 'profi'}}">
                            @if ($card->user->hasRole('vip'))
                                <div class="first__top-title flex">
                                    <p class="upper">Vip</p>
                                    <div class="diamonds"></div>
                                </div>
                            @elseif ($card->user->hasRole('profi'))
                                <div class="first__top-title flex">
                                    <p class="upper">Profi</p>
                                    <div class="brief"></div>
                                </div>
                            @endif
                            <div class="first__avatar"
                                 style="background-image: url({{ $card->Big_img != null ? asset('storage/portfolio/').'/'.$card->user_id.'/'.$card->Big_img : '' }});">
                                <div class="review_col">
                                    <p>отзывы <span>{{ $card->feedbacks_count }}</span></p>
                                </div>
                            </div>
                        </div>
                        <div class="second flex">
                            <div class="dots">
                                <span class="dots__dot"></span>
                                <span class="dots__dot"></span>
                                <span class="dots__dot"></span>
                                <span class="dots__dot"></span>
                                <span class="dots__dot"></span>
                                <span class="dots__dot"></span>
                                <span class="dots__dot"></span>
                                <span class="dots__dot"></span>
                                <span class="dots__dot"></span>
                                <span class="dots__dot"></span>
                            </div>
                            <div class="second__information">
                                <p class="second__position">{{$card->sub_section->name}}</p>
                                <p class="second__name">{{ $card->user->first_name }} {{ $card->user->last_name }} {{ $card->user->patronymic }}</p>
                                <div class="ability">
                                    {{ mb_substr($card->description, 0, 160) }}
                                </div>
                                <div class="buttons flex justify-content-around">
                                    <form action="/about/{{ $card->id }}">
                                        <button class="btn btn_small">Подробнее</button>
                                    </form>
                                    <form action="https://wa.me/{{str_replace([' ', '(', ')', '-'], '', $card->whatsapp)}}" target="_blank">
                                        <button class="btn btn_small">WhatsApp</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        @if ($ads_right != null)
            <div class="advertizing">
                <img src="{{ asset('storage/').'/'.$ads_right->img }}"/>
            </div>
        @endif
    </div>
    @foreach ($topUserCards as $card)
        <div class="top-specialists_mob ">
            <div class="block">
                <div class="left flex">
                    @if ($card->user->hasRole('vip'))
                        <!-- <div class="vip_diamond">
                            <img src="/images/samples/vip.png"/>
                            <p>VIP</p>
                        </div> -->
                        <div class="vip_diamond">
                            <div class="status">
                                <img src="/images/samples/vip.png"/>
                                <p>VIP</p>
                            </div>
                            <div class="reviews_col flex">
                                <span>{{ $card->feedbacks_count }}</span>
                            </div>
                        </div>
                        
                    @elseif ($card->user->hasRole('profi'))
                        <!-- <div class="vip_diamond">
                            <div class="brief"></div>  
                            <p>Profi</p>
                        </div> -->
                        <div class="vip_diamond">
                            <div class="status">
                                <div class="brief"></div>
                                <p>Profi</p>
                            </div>
                            <div class="reviews_col flex">
                                {{ $card->feedbacks_count }}
                            </div>
                        </div>
                    @endif
                    <div class="image_avatar">
                        <img src="{{$card->Big_img != null ? asset('storage/portfolio/').'/'.$card->user_id.'/'.$card->Big_img : ''}}">
                    </div>
                    <!-- <div class="image_avatar">
                        <img src="{{$card->Big_img != null ? asset('storage/portfolio/').'/'.$card->user_id.'/'.$card->Big_img : ''}}"/>
                        <div class="reviews_col flex">
                            отзывы
                            <span>{{ $card->feedbacks_count }}</span>
                        </div>
                    </div> -->
                </div>
                <div class="right">
                    <div class="title"> {{$card->sub_section->name}}</div>
                    <div class="name"> {{ $card->user->first_name }} {{ $card->user->last_name }} {{ $card->user->patronymic }} </div>
                    <div class="details">
                        {{ mb_substr($card->description, 0, 100) }}
                    </div>
                    <div class="buttons flex justify-content-between">
                        <button onclick="location.href='/about/{{ $card->id }}'"
                                class="btn btn_btnMob flex">
                            <i class="icon-mob_arrow_near_button"></i>
                            Подробнее
                        </button>
                        <button onclick="location.href='https://wa.me/{{str_replace([' ', '(', ')', '-'], '', $card->whatsapp)}}'"
                                class="btn btn_btnMob flex">
                            <i class="icon-mob_arrow_near_button"></i>
                            WhatsApp
                        </button>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
@endif